spring:
  application:
    name: socket
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
        url: ${SPRING_ADMIN:http://localhost:8080}
        username: admin
        password: admin-password

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081

